<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="beck-PC" name="pytest" skipped="0" tests="1" time="59.044" timestamp="2020-04-18T20:34:46.746643"><testcase classname="test_cases.test_invest.TestInvest" file="test_cases\test_invest.py" line="9" name="test_invest_success" time="55.360"><failure message="AssertionError: assert 6168795383.0 == (6168795383.98 + 1000)
 +  where 6168795383.0 = float(&apos;6168795383&apos;)
 +  and   6168795383.98 = float(&apos;6168795383.98&apos;)">self = &lt;test_cases.test_invest.TestInvest object at 0x0000000003FF1358&gt;
common_driver = &lt;appium.webdriver.webdriver.WebDriver (session=&quot;2564c28b-04a8-4d4e-9b85-af6fc1db3195&quot;)&gt;

    @pytest.mark.fail
    #@pytest.mark.flaky(reruns=1, reruns_delay=2)
    def test_invest_success(self, common_driver):
        WelcomePage(common_driver).swipe_screen()
        WelcomePage(common_driver).click_experience_now()
        LoginPage(common_driver).click_register_login()
        LoginPage(common_driver).input_phone(login_success_data[&quot;phone&quot;])
        LoginPage(common_driver).input_pwd(login_success_data[&quot;pwd&quot;])
        IndexPage(common_driver).click_later()
        InvestPage(common_driver).enter_invest()
        before_invest_money = InvestPage(common_driver).get_user_left_money()
        InvestPage(common_driver).input_invest_money(invest_success_data[&quot;money&quot;])
        InvestPage(common_driver).invest_now()
        InvestPage(common_driver).click_confirm()
        InvestPage(common_driver).click_back()
        IndexPage(common_driver).click_me()
        after_invest_money = UserInfoPage(common_driver).get_user_left_money()
&gt;       assert float(before_invest_money) == float(after_invest_money) + invest_success_data[&quot;check&quot;]
E       AssertionError: assert 6168795383.0 == (6168795383.98 + 1000)
E        +  where 6168795383.0 = float(&apos;6168795383&apos;)
E        +  and   6168795383.98 = float(&apos;6168795383.98&apos;)

test_cases\test_invest.py:27: AssertionError</failure></testcase></testsuite></testsuites>