Thu, 16 Apr 2020 22:58:19  remote_connection.py  __init__ [line:117] INFO Could not connect to port 4723 on host 127.0.0.1
Thu, 16 Apr 2020 22:58:19  remote_connection.py  __init__ [line:136] INFO Could not get IP address for host: 127.0.0.1
Thu, 16 Apr 2020 22:58:20  connectionpool.py  urlopen [line:662] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000000BED0518>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
Thu, 16 Apr 2020 22:58:21  connectionpool.py  urlopen [line:662] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000000BED06D8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
Thu, 16 Apr 2020 22:58:22  connectionpool.py  urlopen [line:662] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000000BED0898>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
